# Generated by Django 2.2.1 on 2019-07-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configs',
            new_name='Config',
        ),
    ]
