# Generated by Django 2.2.1 on 2019-05-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190518_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
