# Generated by Django 2.2.1 on 2019-05-17 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190518_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='fullname',
            field=models.CharField(default=datetime.datetime(2019, 5, 17, 20, 25, 26, 255140, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
