# Generated by Django 2.2.1 on 2019-05-25 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190518_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='roll_number',
            field=models.CharField(default=datetime.datetime(2019, 5, 25, 3, 19, 48, 629585, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
