# Generated by Django 2.2.1 on 2019-07-06 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentinfo_roll_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminInfo',
        ),
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='staffinfo',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='staffinfo',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='fullname',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default=datetime.datetime(2019, 7, 6, 6, 54, 46, 429945, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='accounts.StaffInfo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='accounts.StudentInfo'),
        ),
    ]
