# Generated by Django 2.2.1 on 2019-07-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190706_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
