# Generated by Django 2.2.1 on 2019-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190718_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='date_enrolled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
