# Generated by Django 2.2.1 on 2019-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190720_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
