# Generated by Django 2.2.1 on 2019-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190721_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
