# Generated by Django 2.2.1 on 2019-09-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentinfo_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='roll_number',
            new_name='gr_number',
        ),
    ]
