# Generated by Django 2.2.1 on 2019-09-19 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190906_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='address',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 11, 38, 32, 311818)),
        ),
    ]
