# Generated by Django 2.2.1 on 2019-09-19 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190919_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 6, 41, 40, 166018, tzinfo=utc)),
        ),
    ]
