# Generated by Django 2.2.1 on 2019-09-19 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190919_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='date_hired',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 12, 11, 43, 213175, tzinfo=utc)),
        ),
    ]
