# Generated by Django 2.2.1 on 2019-09-21 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190921_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
