# Generated by Django 2.2.1 on 2019-09-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190921_1417'),
        ('accounts', '0017_auto_20190920_1540'),
    ]

    operations = [
    ]
