# Generated by Django 2.2.1 on 2019-10-08 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20190923_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
