# Generated by Django 2.2.1 on 2019-05-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20190522_2255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'grade')},
        ),
    ]
