# Generated by Django 2.2.1 on 2019-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_feechallan_feestructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name_plural': 'Income Categories'},
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='feechallan',
            name='description',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='description',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='description',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='description',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
