# Generated by Django 2.2.1 on 2019-05-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20190512_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='feechallan',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
