# Generated by Django 2.2.1 on 2019-05-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20190512_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='incomeitem',
            old_name='name',
            new_name='title',
        ),
    ]
