# Generated by Django 2.2.1 on 2019-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20190518_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='break_down',
            field=models.TextField(max_length=2048),
        ),
    ]
