# Generated by Django 2.2.1 on 2019-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_auto_20190620_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feechallan',
            name='paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
