# Generated by Django 2.2.1 on 2019-07-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioncategory',
            old_name='transaction_type',
            new_name='category_type',
        ),
    ]
