# Generated by Django 2.2.1 on 2019-07-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_auto_20190710_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incomeitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='ExpenseItem',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
        migrations.DeleteModel(
            name='IncomeItem',
        ),
    ]
