# Generated by Django 2.2.1 on 2019-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_auto_20190710_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Debit'), (2, 'Credit')], default=1),
            preserve_default=False,
        ),
    ]
