# Generated by Django 2.2.1 on 2019-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
