# Generated by Django 2.2.1 on 2019-09-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_auto_20190913_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
