# Generated by Django 2.2.1 on 2019-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_auto_20190913_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='late_fee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
