# Generated by Django 2.2.1 on 2019-10-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20190522_2256'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionsubject',
            unique_together={('subject', 'section')},
        ),
    ]
