# Generated by Django 2.2.1 on 2019-10-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20191016_1629'),
        ('academics', '0003_auto_20191016_0325'),
    ]

    operations = [
    ]
