# Generated by Django 2.2.1 on 2019-10-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentassessment_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassessment',
            name='attendance',
        ),
    ]
