# Generated by Django 2.2.1 on 2019-10-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_studentassessment_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessment',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.Assessment'),
        ),
    ]
