# Generated by Django 2.2.1 on 2019-10-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_session'),
        ('structure', '0004_auto_20190522_2256'),
        ('academics', '0008_auto_20191023_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='graded',
        ),
        migrations.AddField(
            model_name='assessment',
            name='consolidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='section_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.SectionSubject'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='common.Session'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('consolidated', models.BooleanField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='structure.Section')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='common.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='academics.Exam'),
        ),
    ]
