# Generated by Django 2.2.1 on 2019-10-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='heading',
            new_name='title',
        ),
    ]
