# Generated by Django 2.2.1 on 2019-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20191008_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.IntegerField(choices=[(1, 'Organization'), (2, 'Class'), (3, 'Section'), (4, 'Staff'), (5, 'Teacher'), (6, 'Parent'), (7, 'Student')], default=1),
        ),
    ]
