# Generated by Django 2.2.1 on 2019-07-29 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190729_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 20, 46, 33, 553387, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 20, 46, 41, 326114, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
