# Generated by Django 2.2.1 on 2019-10-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_session'),
        ('attendance', '0005_auto_20191009_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystaffattendance',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='common.Session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystudentattendance',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='common.Session'),
            preserve_default=False,
        ),
    ]
