# Generated by Django 2.2.1 on 2019-10-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20191009_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendanceitem',
            name='comments',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendanceitem',
            name='comments',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
