# Generated by Django 2.2.1 on 2019-10-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20191009_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendanceitem',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_student_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
